### ISSUE TITLE
'use strict' in index.js

### ISSUE THREAD

**Issue by sirhoe** [TonyFNZ/bunyan-sumologic#1]
Got a simple error while I was trying to run it.

.. /node_modules/bunyan-sumologic/index.js:50
    let rewriteLevels = true;
    ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

Can you add 'use strict' to the top of the file?

**Comment by sirhoe** [comment]
Pull request #2

**Comment by TonyFNZ** [comment]
Merged and included in v1.0.1
